package de.hhu.bsinfo.observatory.app.command;

import de.hhu.bsinfo.observatory.app.Application;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.Callable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine;

@CommandLine.Command(
        name = "clean",
        description = "Cleans up any files generated by the benchmark.%n",
        showDefaultValues = true,
        separator = " ")
public class Clean implements Callable<Void> {

    private static final Logger LOGGER = LoggerFactory.getLogger(Application.class);

    @CommandLine.Parameters(
            index = "0"
    )
    private String benchmarkName = "";

    @Override
    public Void call() {
        if(benchmarkName.isEmpty()) {
            LOGGER.error("Please specify a benchmark name or 'all' to delete all results");
            return null;
        }

        try {
            if (benchmarkName.toLowerCase().equals("all")) {
                deleteDirectory(new File("result/"));
            } else {
                deleteResults(new File("result/"), benchmarkName.toLowerCase());
            }
        } catch (IOException e) {
            LOGGER.error("Unable to delete results");
            return null;
        }

        LOGGER.info("Successfully deleted results");
        return null;
    }

    private void deleteDirectory(File directory) throws IOException {
        if(!directory.exists()) {
            return;
        }

        File[] files = directory.listFiles();

        if(files != null) {
            for(File file : files) {
                if(file.isDirectory()) {
                    deleteDirectory(file);
                } else {
                    if(!file.delete()) {
                        throw new IOException("Unable to delete file '" + file.getPath() + "'");
                    }
                }
            }
        }
    }

    private void deleteResults(File directory, String benchmarkName) throws IOException {
        if(!directory.exists()) {
            return;
        }

        File[] files = directory.listFiles();

        if(files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    deleteResults(file, benchmarkName);
                } else {
                    if (file.getName().toLowerCase().startsWith(benchmarkName.toLowerCase())) {
                        if (!file.delete()) {
                            throw new IOException("Unable to delete file '" + file.getPath() + "'");
                        }
                    }
                }
            }
        }
    }
}
