package de.hhu.bsinfo.observatory.app.command;

import de.hhu.bsinfo.observatory.plot.MainWindow;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.Callable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine;

@CommandLine.Command(
        name = "plot",
        description = "Plots results generated by benchmark runs.%n",
        showDefaultValues = true,
        separator = " ")
public class Plot implements Callable<Void> {

    private static final Logger LOGGER = LoggerFactory.getLogger(Plot.class);

    @Override
    public Void call() throws IOException {
        File resultDirectory = new File("result/");

        if(!resultDirectory.exists() || !resultDirectory.isDirectory()) {
            LOGGER.error("Unable to open result directory '{}'", resultDirectory.getPath());
            return null;
        }

        MainWindow window = new MainWindow(resultDirectory);
        window.setVisible(true);

        return null;
    }
}
